### ISSUE TITLE
line 47 of the doctor spec is incorrect

### ISSUE THREAD

**Issue by stephenkeating** [learn-co-curriculum/ruby-objects-has-many-through-lab#38] opened 2019-10-13 11:32 UTC
Unless I'm mistaken, the arguments are in the wrong order in the doctor test. 

Line 47 looks like this:
doctor_who.new_appointment(hevydevy, 'Friday, January 32nd')

It should look like this:
doctor_who.new_appointment('Friday, January 32nd', hevydevy)

**Comment by sgharms** [comment] 2019-10-15 14:34
@stephenkeating 

I might be missing something here but line 47 in the `spec/04_doctor_spec.rb`

```ruby
doctor_who.new_appointment(hevydevy, 'Friday, January 32nd')
```
So that's a patient and a date. That seems to conform with the specification in the README:

> The Doctor class needs an instance method, #new_appointment, that takes in an instance of the Patient class and a date, and creates a new Appointment. That Appointment should know that it belongs to the doctor

As far as I can tell, that's what's happening here.

Let me know whether I missed something.
>

**Comment by stephenkeating** [comment] 2019-10-15 16:29
I think the arguments are in the wrong order, putting patient into the date parameter and date into the patient parameter, based on how the initialize was setup.

Stephen
310-938-4400

**Comment by sgharms** [comment] 2019-10-21 12:24
@stephenkeating Could you specify where the "initialize was setup" statement you're referring to is?

**Comment by stephenkeating** [comment] 2019-10-22 13:06
The appointment "def initialize” takes has the parameters in a different order. So when the test passes arguments, they get mixed up.

Stephen
310-938-4400

**Comment by sgharms** [comment] 2019-10-24 15:23
@stephenkeating  I'm still struggling to understand the bug here. Here's my understanding of the problem. Assuming I've got it right here, I don't think this is actually a bug. Let me explain.

The [README says](https://github.com/learn-co-curriculum/ruby-objects-has-many-through-lab/blame/master/README.md#L85-L87)

> The `Doctor` class needs an instance method, `#new_appointment`, that takes in an instance of the `Patient` class and a date, and creates a new `Appointment`. That Appointment` should know that it belongs to the doctor

The order of parameters it receives can specify in whatever way it likes: in this case "Patient and a date."

This is tested in https://github.com/learn-co-curriculum/ruby-objects-has-many-through-lab/blob/master/spec/04_doctor_spec.rb#L47 

Now, _completedly unrelated_ to the methods of `Doctor`, are concerns about `Appointment`s.

The README [says](https://github.com/learn-co-curriculum/ruby-objects-has-many-through-lab/blame/master/README.md#L123-L124):

 > An `Appointment` should be initialized with a date (as a string, like `"Monday, August 1st"`), a patient, and a doctor. The `Appointment` should be saved in the `@@all` array.

The `Appointment#initialize` method can specify the order of parameters _it_ receives in whatever way it likes: it likes "Date, then Patient, then Doctor"

This is verified by the spec: https://github.com/learn-co-curriculum/ruby-objects-has-many-through-lab/blob/master/spec/05_appointment_spec.rb#L22

As a result, these two methods have no _necessary_ connection to each other. The `Doctor`'s method can take arguments in any order. When it _in turn_ calls Appointment, it needs to be sure to honor `Appointment`'s contract, but there's no requirement that its own parameter set mirror `Appointment`'s. The internals of `Doctor#new_appointment` handle the re-ordering of arguments that it passes to `Appointment#new`.

As such, I think this is "not a bug." Can you verify my understanding of your problem here?

**Comment by stephenkeating** [comment] 2019-10-26 17:04
It’s been a couple weeks since I looked at it, so maybe I was wrong. I don’t remember being able to get the arguments to pass to the correct parameters, but it’s possible I just didn’t know how to do that at the time.

Stephen
310-938-4400

**Comment by sgharms** [comment] 2019-10-28 13:50
OK, thanks for the update. Closing.

**Closed as completed by sgharms** 2019-10-28 13:50 UTC
