### ISSUE TITLE
Additional end needed.Line 42 of patient.spec.rb file in 'describe#appointments'. 

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/ruby-objects-has-many-through-lab#26] opened 2018-10-07 14:37 UTC
Line 42 of the patient.spec.rb file needs an extra "end".   It is in the "describe #appointments" area.

I had multiple syntax errors in running LEARN, pointing to an "end" and looked through all of my files, and a Tech Coach (Rochel) found this while in our Zoom session. Thanks.

**Comment by drakeltheryuujin** [comment] 2018-10-08 18:15
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail where the issue is or when the issue occurs, 
I'd be happy to take a second look!

As always, thanks for contributing! 💙

**Closed as completed by drakeltheryuujin** 2018-10-08 18:15 UTC
Labels: Test
