### ISSUE TITLE
should song.artist be read-only?

### ISSUE THREAD

**Issue by geluso** [learn-co-curriculum/ruby-objects-has-many-through-lab#30] opened 2019-01-31 19:52 UTC
Tests failed because I made my `song.artist` read-only.  The tests construct a song passing in name, artist and genre. Then the test immediately manually assigns the same artist again.

```
ninety_nine_problems = Song.new("99 Problems", jay_z, rap)
ninety_nine_problems.artist = jay_z
```

I initially wrote my song class like this keeping each property read-only. 

```
class Song
    attr_reader :name, :artist, :genre

    def initialize(name, artist, genre)
        @name = name
        @artist = artist
        @genre = genre
    end
end
```

The spec doesn't say anything about the artist being writable. Having it this way has:

**Pros:** forces students to look at the test error output and realize and learn what's going on.
**Cons:** making `artist` writable is non-intuitive and unspecified.

Is this inentional and should we leave it this way, or should we remove the manual assignment to artist from the test spec?

See pull request removing manual assignment for easy merge if we want to change to go that way.

**Comment by maxwellbenton** [comment] 2019-07-26 20:51
Hi @geluso,

Looks like you've already merged in a PR fix for this, but I took a look while updating this lesson and confirmed that artist will now work as a read-only attribute. Thanks for spotting this and providing this feedback!

**Closed as completed by maxwellbenton** 2019-07-26 20:51 UTC
